[package]
name = "haulage-ru"
version = "0.1.0"
authors = ["Matt Johnson <matt9j@cs.washington.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
