flowLogInterval: "20m"
userLogInterval: "1m"

# Deprecated
# interface: "wlp1s0"

upstreamInterface: "eth0"
subscriberInterface: "ogstun"

userSubnet: "10.45.0.0/24"
ignoredUserAddresses: ["10.45.0.1"]

custom:
  reenablePollInterval: "5s"
  dbLocation: "haulage_db"
  dbUser: "haulage_db"
  dbPass: "haulage_db"
  dbAutoUpgrade: true
