[profile.release]
lto = true

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-L", "/usr/lib/aarch64-linux-gnu"]

[target.x86_64-unknown-linux-gnu]
# If you are building from a non-x86_64 machine, you will need to point to your
# x86_64 linker here. This is left commented by default to allow native cargo
# builds on the common x86_64 architecture from different linux distros that put
# their linker in a different place. (the location below works for Debian)

# linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-cpu=haswell"]
